# a = int(input("Введите целочисленное число: "))
# b = float(input("Введите дробное число: "))
# (c, d, f, g) = (0, 3, 5, 9.8)
# l = a + b
# print(type(l))
# print(l)
# print(c + d + f + g + l)
# l = str(l)
# print(type(l))
# t = input("Введите целочисленное число: ")
# y = input("Введите целочисленное число: ")
# print(t + y)
# print(type(t), type(y))
# print("* * * * * \n \n")
# print(1 + 5)
# a = input("Пользователь вводит строку: ")
# a = float(a)
# print(type(a))
# print(a)
